Algoritmo "variaveis_planilha"
Var
// Seção de Declarações das variáveis 
  idade  : inteiro
  altura : real
  nome : caractere
  casado : logico
  vet_uni : vetor [0..4] de real
  vet_bi: vetor [0..1,0..3] de inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   idade <- 30
   altura <- 1.81
   nome <- "Ricardo"
   casado <- verdadeiro
   vet_uni [2] <- 25
   vet_bi [0,2] <- 50
Fimalgoritmo